### ISSUE TITLE
Feature Request: Ability to add custom domain

### ISSUE THREAD

**Issue by kmoberg** [NFarrington/vatsim-url-shortener#8]
Hi, 

Our ARTCC is looking into utilizing URL shortening for multiple things, but it would be really cool if there was a way, even if it's a manual way somehow, to add our own domain to our organization, not just the vats.im domains.

**Comment by NFarrington** [comment]
Hey @kmoberg, I'll look into this for you and let you know what I come up with.

**Comment by NFarrington** [comment]
Private domain permissions have been implemented via https://github.com/NFarrington/vatsim-url-shortener/commit/b7241c84e91f7b99bd7b05b4060537a7391df96f, which will allow members of specific organizations to create URLs for private domains.

@kmoberg As the process for setting up a custom domain will require an infrastructure change in order for the domain to be accepted by the existing web servers, this will need to be a manual process. If you'd like to discuss further and arrange setting up a custom domain, please send me an email at support@vats.im.
